#include "version.h"

// DEFINEs the BULID_TIMESTAMP compiler constant.
// Created by set_build_timestamp.py, which is beside platformio.ini
#include "autogenerated_build_timestamp.h"

#include <Arduino.h>

namespace version {
    String getBuildTime() { return BUILD_TIMESTAMP; }
}