version: '3'
services:
  server:
    container_name: fof
    privileged: true
    build:
      context: ./server
      dockerfile: Dockerfile
    tmpfs:
      - /tmp:size=10m
    ports:
      - 80:80        # FCC web server
      - 1883:1883    # unencrypted MQTT
      - 8081:8081    # NanoMQ HTTP rest api
      - 9001:9001
      - 123:123      # ntp
      - 123:123/udp  # ntp broadcast (not needed?)
    logging:
      driver: "local"
      options:
        max-size: "10m"      # Maximum log file size
        max-file: "3"        # Maximum number of log files to retain
        compress: "true"     # Compress rotated log files
        mode: "non-blocking"
    volumes:
      - ./server/code:/app/code
      - ./server/flower_control_center:/app/flower_control_center
      - ./server/config:/app/config
      - ./deployments:/app/deployments
      - ./fake_field:/app/fake_field
      - ./gsa:/app/gsa
      - ./va:/app/va
    command: ./startup.sh
  # nanomq:
  #   image: emqx/nanomq:latest
  #   container_name: nanomq
  #   privileged: true
  #   ports:
  #     #- "1883:1883"
  #     #- "9001:8083"
  #     - "8883:8883"
  #   restart: always

