version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 1883:1883
      - 9001:9001
    volumes:
      - ./server/code:/app/code
      - ./server/flower_control_center:/app/flower_control_center
      - ./server/config:/app/config
      - ./deployments:/app/deployments
    depends_on:
      - redis
    command: ./startup.sh

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
      - 8001:8001
