name: "Default Test Field"
description: "This deployment is used for internal testing or when no deployment is specified"
redis:
  host: 'redis'
  port: 6379
  liveflowers: 'flowers-live:'
  deadflowers: 'dead-flowers:'
broker:
  host: 'server'
  port: 1883
  heartbeats: 'flower-heartbeats/'
ntp:
  host: 'server'
  port: 123
field:
  description: "A 100x100 field to simulate the setup at the burn"
  dimensions:
    x: 100
    y: 100
flowers:
  positions:
    'F0:6D:8C':
      x: 10
      y: 10
    'F0:70:1C':
      x: 20
      y: 20
    'F0:6F:04':
      x: 30
      y: 30
    'DA:e7:10':
      x: 40
      y: 40
    'f0:5f:ec':
      x: 50
      y: 50
    'f0:70:ac':
      x: 60
      y: 60
    'f0:5f:e8':
      x: 70
      y: 70
    'f0:70:48':
      x: 80
      y: 80
    'f0:6f:00':
      x: 90
      y: 90



