name: "Dress Rehearsal at Treasure Island"
description: "Grid with 6-foot spacing"
field:
  x: 1000
  y: 1000
  corners:
    - [164, 46]
    - [998, 7]
    - [1186, 491]
    - [ 13, 516 ]
flowers:
  "BA:5A:00": { id:  135,   x:  50,   y:  50 }
  "F0:70:94": { id:  158,   x: 410,   y:  50 }
  "F0:60:60": { id:  152,   x: 482,   y:  50 }
  "BA:82:88": { id:  160,   x:  50,   y: 122 }
  "BB:BB:BB": { id:  162,   x: 122,   y: 122 }
  "C0:2D:C8": { id:  153,   x: 194,   y: 122 }
  "C0:2B:58": { id:  155,   x: 266,   y: 122 }
  "C0:37:D0": { id:  159,   x: 338,   y: 122 }
  "CC:F7:F8": { id:  156,   x: 410,   y: 122 }
  "BA:5F:60": { id:  141,   x: 482,   y: 122 }
  "C0:49:C0": { id:  116,   x: 554,   y: 122 }
  "BA:7F:18": { id:  104,   x: 626,   y: 122 }
  "C0:39:64": { id:   90,   x: 698,   y: 122 }
  "CD:0D:C4": { id:  111,   x: 770,   y: 122 }
  "C0:17:A0": { id:   95,   x: 842,   y: 122 }
  "F0:6E:E4": { id:  103,   x: 914,   y: 122 }
  "BA:69:98": { id:  123,   x: 986,   y: 122 }
  "BA:7A:68": { id:  146,   x:  50,   y: 194 }
  "CC:FE:D0": { id:  139,   x: 122,   y: 194 }
  "BA:5C:7C": { id:  134,   x: 194,   y: 194 }
  "C0:10:6C": { id:  154,   x: 266,   y: 194 }
  "CC:FE:C4": { id:  122,   x: 338,   y: 194 }
  "F0:6E:C8": { id:  142,   x: 410,   y: 194 }
  "C0:11:A0": { id:  143,   x: 482,   y: 194 }
  "BA:89:D4": { id:   85,   x: 554,   y: 194 }
  "CC:FE:7C": { id:   70,   x: 626,   y: 194 }
  "BA:40:24": { id:   98,   x: 698,   y: 194 }
  "C0:35:30": { id:   92,   x: 770,   y: 194 }
  "C0:11:28": { id:   87,   x: 842,   y: 194 }
  "BA:5F:48": { id:   82,   x: 914,   y: 194 }
  "C0:21:08": { id:   94,   x: 986,   y: 194 }
  "F0:70:28": { id:  147,   x:  50,   y: 266 }
  "BA:3B:98": { id:  138,   x: 122,   y: 266 }
  "BA:68:98": { id:  140,   x: 194,   y: 266 }
  "D8:92:64": { id:  144,   x: 266,   y: 266 }
  "C0:36:9C": { id:  137,   x: 338,   y: 266 }
  "F0:6F:E0": { id:  128,   x: 410,   y: 266 }
  "C0:2B:68": { id:  132,   x: 482,   y: 266 }
  "BA:67:D0": { id:  109,   x: 554,   y: 266 }
  "CD:06:64": { id:  105,   x: 626,   y: 266 }
  "C0:2F:98": { id:  112,   x: 698,   y: 266 }
  "CC:1E:10": { id:  115,   x: 770,   y: 266 }
  "BA:7E:A0": { id:  118,   x: 842,   y: 266 }
  "C0:2B:F0": { id:   86,   x: 914,   y: 266 }
  "C0:4A:B8": { id:   91,   x: 986,   y: 266 }
  "C0:11:10": { id:  149,   x:  50,   y: 338 }
  "C0:35:18": { id:  136,   x: 122,   y: 338 }
  "C0:42:8C": { id:  145,   x: 194,   y: 338 }
  "C0:1E:00": { id:  129,   x: 266,   y: 338 }
  "C0:1E:30": { id:  131,   x: 338,   y: 338 }
  "C0:20:0C": { id:  121,   x: 410,   y: 338 }
  "AA:AA:AA": { id:  161,   x: 482,   y: 338 }
  "BA:7C:84": { id:  110,   x: 554,   y: 338 }
  "BA:3F:AC": { id:   96,   x: 626,   y: 338 }
  "C0:37:90": { id:  106,   x: 698,   y: 338 }
  "C0:2B:98": { id:  102,   x: 770,   y: 338 }
  "C0:3B:C8": { id:   97,   x: 842,   y: 338 }
  "CC:FE:D4": { id:  127,   x: 914,   y: 338 }
  "BA:7B:EC": { id:  117,   x: 986,   y: 338 }
  "C0:0D:94": { id:  126,   x:  50,   y: 410 }
  "C0:1E:DC": { id:  133,   x: 122,   y: 410 }
  "CC:1E:08": { id:  151,   x: 194,   y: 410 }
  "C0:34:BC": { id:  130,   x: 266,   y: 410 }
  "BA:8C:60": { id:  150,   x: 338,   y: 410 }
  "C0:11:0C": { id:  148,   x: 410,   y: 410 }
  "C0:39:94": { id:  157,   x: 482,   y: 410 }
  "BA:7C:60": { id:  114,   x: 554,   y: 410 }
  "C0:17:DC": { id:   93,   x: 626,   y: 410 }
  "BA:8C:A4": { id:   83,   x: 698,   y: 410 }
  "C0:1F:90": { id:   84,   x: 770,   y: 410 }
  "CC:FA:D0": { id:   88,   x: 842,   y: 410 }
  "D5:4B:5C": { id:   89,   x: 914,   y: 410 }
  "BA:89:B8": { id:  119,   x: 986,   y: 410 }
  "C0:10:C4": { id:   17,   x: 482,   y: 482 }
  "F0:70:90": { id:   27,   x: 122,   y: 554 }
  "C0:3B:F8": { id:   24,   x: 194,   y: 554 }
  "F0:6F:E4": { id:   20,   x: 266,   y: 554 }
  "F0:5F:EC": { id:    5,   x: 338,   y: 554 }
  "C0:0E:1C": { id:   37,   x: 410,   y: 554 }
  "F0:70:80": { id:   19,   x: 482,   y: 554 }
  "BA:67:C8": { id:   50,   x: 554,   y: 554 }
  "F0:6E:E8": { id:   68,   x: 626,   y: 554 }
  "C0:3B:98": { id:   62,   x: 698,   y: 554 }
  "C0:1C:94": { id:   75,   x: 770,   y: 554 }
  "C0:04:D4": { id:   59,   x: 842,   y: 554 }
  "C0:38:6C": { id:   80,   x: 914,   y: 554 }
  "CC:FE:B8": { id:   41,   x: 986,   y: 554 }
  "BA:68:78": { id:   14,   x:  50,   y: 626 }
  "CC:FC:C0": { id:   26,   x: 122,   y: 626 }
  "C0:F0:2C": { id:   28,   x: 194,   y: 626 }
  "C0:21:F0": { id:   31,   x: 266,   y: 626 }
  "F0:70:AC": { id:    6,   x: 338,   y: 626 }
  "BA:86:C8": { id:   34,   x: 410,   y: 626 }
  "CD:04:14": { id:   32,   x: 482,   y: 626 }
  "BA:89:D8": { id:   65,   x: 554,   y: 626 }
  "D5:11:80": { id:   73,   x: 626,   y: 626 }
  "C0:10:74": { id:   56,   x: 698,   y: 626 }
  "C0:2F:4C": { id:   63,   x: 770,   y: 626 }
  "CC:FE:90": { id:   61,   x: 842,   y: 626 }
  "C0:2F:8C": { id:   58,   x: 914,   y: 626 }
  "C0:31:58": { id:   49,   x: 986,   y: 626 }
  "C0:36:34": { id:   15,   x:  50,   y: 698 }
  "C0:39:4C": { id:   40,   x: 122,   y: 698 }
  "F0:70:58": { id:   16,   x: 194,   y: 698 }
  "BA:5F:80": { id:   13,   x: 266,   y: 698 }
  "F0:6F:04": { id:    3,   x: 338,   y: 698 }
  "C0:1E:78": { id:   29,   x: 410,   y: 698 }
  "BA:8C:98": { id:   38,   x: 482,   y: 698 }
  "BA:8D:14": { id:   78,   x: 554,   y: 698 }
  "C0:2B:A0": { id:   46,   x: 626,   y: 698 }
  "C0:2B:44": { id:   48,   x: 698,   y: 698 }
  "C0:1E:34": { id:   66,   x: 770,   y: 698 }
  "C0:38:1C": { id:   74,   x: 842,   y: 698 }
  "C0:21:18": { id:   64,   x: 914,   y: 698 }
  "C0:12:B8": { id:   55,   x: 986,   y: 698 }
  "C0:30:24": { id:   12,   x:  50,   y: 770 }
  "F0:70:48": { id:    8,   x: 122,   y: 770 }
  "F0:6E:D4": { id:   10,   x: 194,   y: 770 }
  "CD:10:60": { id:   18,   x: 266,   y: 770 }
  "DA:E7:10": { id:    4,   x: 338,   y: 770 }
  "C0:0D:A4": { id:   36,   x: 410,   y: 770 }
  "BA:59:F4": { id:   22,   x: 482,   y: 770 }
  "CC:F7:C4": { id:   57,   x: 554,   y: 770 }
  "CD:10:54": { id:   44,   x: 626,   y: 770 }
  "BA:7A:EC": { id:   43,   x: 698,   y: 770 }
  "BA:3E:10": { id:   47,   x: 770,   y: 770 }
  "C0:19:44": { id:   54,   x: 842,   y: 770 }
  "CD:06:40": { id:   67,   x: 914,   y: 770 }
  "CC:33:A0": { id:   72,   x: 986,   y: 770 }
  "BA:6F:A0": { id:   25,   x:  50,   y: 842 }
  "F0:5F:E8": { id:    7,   x: 122,   y: 842 }
  "C0:12:44": { id:   21,   x: 194,   y: 842 }
  "C0:1E:80": { id:   33,   x: 266,   y: 842 }
  "C0:38:FC": { id:   23,   x: 338,   y: 842 }
  "CC:FE:C8": { id:   35,   x: 410,   y: 842 }
  "BA:79:EC": { id:   30,   x: 482,   y: 842 }
  "F0:6E:DC": { id:   77,   x: 554,   y: 842 }
  "C0:38:D0": { id:   52,   x: 626,   y: 842 }
  "CC:FC:40": { id:   60,   x: 698,   y: 842 }
  "BA:8D:1C": { id:   42,   x: 770,   y: 842 }
  "C0:49:18": { id:   51,   x: 842,   y: 842 }
  "BA:53:58": { id:   45,   x: 914,   y: 842 }
  "BA:8D:70": { id:   53,   x: 986,   y: 842 }
